from __future__ import annotations

import contextlib
import logging
import os
import sqlite3
import time
from dataclasses import dataclass

import duckdb

logger = logging.getLogger(__name__)


@dataclass
class ConversionResult:
    """What a successful conversion produced."""

    target: str
    tables: int
    elapsed: float
    """Wall clock duration of the conversion, in seconds."""


def _quote_identifier(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _format_duration(seconds: float) -> str:
    if seconds < 1:
        return f"{seconds * 1000:.2f} ms"
    return f"{seconds:.2f} s"


def _remove_quietly(path: str) -> None:
    for candidate in (path, path + ".wal"):
        try:
            os.remove(candidate)
        except OSError:
            pass


def _brackets_to_quotes(sql: str) -> str:
    """Rewrite sqlite's [bracket] identifiers into standard "double quoted" ones.

    Quoted runs are copied verbatim so that a `[` inside a string literal survives.
    """

    out = []
    index = 0
    length = len(sql)

    while index < length:
        char = sql[index]

        if char in "'\"`":
            end = index + 1
            while end < length:
                if sql[end] == char:
                    if end + 1 < length and sql[end + 1] == char:
                        end += 2
                        continue
                    break
                end += 1
            out.append(sql[index : end + 1])
            index = end + 1

        elif char == "[":
            end = sql.find("]", index)
            if end == -1:
                out.append(char)
                index += 1
            else:
                out.append(_quote_identifier(sql[index + 1 : end]))
                index = end + 1

        else:
            out.append(char)
            index += 1

    return "".join(out)


def _copy_indexes(conn: duckdb.DuckDBPyConnection, sqlite_path: str) -> None:
    """Recreate the source indexes, translating sqlite quoting on the way."""

    with contextlib.closing(sqlite3.connect(sqlite_path)) as source:
        indexes = source.execute(
            "SELECT name, sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL"
        ).fetchall()

    for name, sql in indexes:
        try:
            conn.sql(_brackets_to_quotes(sql))
        except duckdb.Error as error:
            logger.warning("Could not recreate index %s: %s", name, error)


def _copy_tables(
    conn: duckdb.DuckDBPyConnection, tables: list[tuple[str, str]]
) -> None:
    """Recreate each table then fill it from the attached database."""

    for table_name, ddl in tables:
        # This DDL is regenerated by duckdb from the attached catalog, so unlike
        # sqlite's own it always parses, and it still carries the primary keys
        # and the NOT NULL constraints.
        conn.sql(ddl)
        quoted = _quote_identifier(table_name)
        conn.sql(f"INSERT INTO {quoted} SELECT * FROM __other.{quoted}")


def sqlite_to_duckdb(
    sqlite_db: str | os.PathLike[str],
    duck_db: str | os.PathLike[str],
    *,
    overwrite: bool = False,
) -> ConversionResult:
    """Copy a sqlite database into a new duckdb database.

    Tables, data, primary keys, NOT NULL constraints and indexes are copied.
    Views and UNIQUE / FOREIGN KEY / CHECK constraints are not: duckdb's sqlite
    extension does not expose them on the attached database.

    Raises FileNotFoundError if `sqlite_db` does not exist, and FileExistsError
    if `duck_db` already exists and `overwrite` is False.
    """

    sqlite_path = os.fspath(sqlite_db)
    duck_path = os.fspath(duck_db)

    if not os.path.exists(sqlite_path):
        raise FileNotFoundError(f"File {sqlite_path} doesn't exist")

    if os.path.exists(duck_path):
        if not overwrite:
            raise FileExistsError(f"Database {duck_path} already exists")
        _remove_quietly(duck_path)

    logger.info("Create %s database", duck_path)
    start_time = time.perf_counter()

    conn = duckdb.connect(duck_path)
    try:
        ## Install sqlite
        conn.sql("INSTALL sqlite; LOAD sqlite;")

        # Bound parameters are not allowed in ATTACH, so escape the quotes ourselves
        source_path = sqlite_path.replace("'", "''")
        conn.sql(f"ATTACH '{source_path}' AS __other (TYPE SQLITE, READ_ONLY)")

        ## Get sqlite Names, along with the CREATE statement duckdb derives for them
        tables = conn.sql(
            "SELECT table_name, sql FROM duckdb_tables WHERE database_name = '__other'"
        ).fetchall()
        logger.info("%d table(s) found", len(tables))

        _copy_tables(conn, tables)
        _copy_indexes(conn, sqlite_path)

        conn.sql("DETACH __other")
    except BaseException:
        # Never leave a half-written database behind: it would trip the
        # "already exists" guard on the next run.
        conn.close()
        _remove_quietly(duck_path)
        raise

    conn.close()

    elapsed = time.perf_counter() - start_time
    logger.info("Done in %s !", _format_duration(elapsed))

    return ConversionResult(target=duck_path, tables=len(tables), elapsed=elapsed)
